### ISSUE TITLE
Missing Main Screen Background Music File

### ISSUE THREAD

**Issue by ben-ashby** [BlissMediaSolutions/Battleships#10]
The battleship code is missing the following resource 'horrodrone.mp3'. 

This is used to play background music in the main menu.

**Comment by BlissMediaSolutions** [comment]
Is this meaning that the file "horrodrone.mp3" is missing? - because its in the source code.
If its a case of a sound file which is never used in the actual Source Code - then its an extra / unused file, & should be noted accordingly.

**Comment by ben-ashby** [comment]
The game is unable to locate the mp3 when it loads, I have not investigated enough to see if this is simply a renamed file or it has been fully deleted.

**Comment by BlissMediaSolutions** [comment]
I think its somehow a bug with your system...
That sound plays for me in the main screen.

i played the sound file thru VLC (so i knew what the sound was), then ran the game & sure enough i get that sound.

Possibly try rebuilding the code & post a screen capture of the error you get.

**Comment by ben-ashby** [comment]
Hmm that's strange. Maybe I will re clone the code just to be sure. 

Thanks for pointing that out :)

**Comment by BlissMediaSolutions** [comment]
I'm thinking this is an OSX specific bug.
If you have a Windows VM, install Git, clone the Repo, then build & run.
If the sound works - then it tells us its a OS platform issue.
