### ISSUE TITLE
Ships not deployed at Mouse Click 

### ISSUE THREAD

**Issue by ben-ashby** [BlissMediaSolutions/Battleships#5]
When player is setting up their ships on the grid the ship is not deployed at the location of the mouse when clicked. 

Ship is deployed on the Y Axis four cells bellow the mouse location cell. 

![image](https://cloud.githubusercontent.com/assets/17717242/14068337/26d8e44c-f4cb-11e5-9963-e52d1b032e14.png)

**Comment by BlissMediaSolutions** [comment]
that's what i was referring to with Bug #2 
https://github.com/BlissMediaSolutions/Battleships/issues/2

**Comment by ben-ashby** [comment]
Thanks for pointing this out, I must have misinterpreted what you meant with Bug #2, I shall close this one off now.
